# Generated by Django 5.0.1 on 2026-01-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_farmernote_farmerreminder_recommendationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('season', models.CharField(blank=True, max_length=80)),
                ('ideal_ph_min', models.FloatField(blank=True, null=True)),
                ('ideal_ph_max', models.FloatField(blank=True, null=True)),
                ('ideal_temp_min', models.FloatField(blank=True, null=True)),
                ('ideal_temp_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=80)),
                ('market', models.CharField(blank=True, max_length=120)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('price_inr_per_quintal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('predicted_price', models.FloatField()),
                ('model_version', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=10)),
                ('crop_name', models.CharField(max_length=80)),
                ('confidence', models.FloatField(default=0.0)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('inputs', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerreminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='soilprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.DeleteModel(
            name='FarmerNote',
        ),
        migrations.DeleteModel(
            name='FarmerReminder',
        ),
        migrations.DeleteModel(
            name='RecommendationHistory',
        ),
        migrations.DeleteModel(
            name='SoilProfile',
        ),
    ]
