# Generated by Django 4.2 on 2026-03-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_crop_croppricerecord_priceprediction_recommendation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='CropPriceRecord',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='PricePrediction',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
