# Generated by Django 6.0.4 on 2026-04-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_soilanalysis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('translated', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['language'], name='core_transl_languag_2c3ce9_idx')],
                'unique_together': {('source_text', 'language')},
            },
        ),
    ]