# recommender/data.py

CROP_LIBRARY = [
    {
        "name": "Rice",
        "season": "Kharif",
        "ph": (5.5, 7.0),
        "temp": (20, 35),
        "humidity": (60, 90),
        "rain": (120, 300),
        "essentials": [
            "Maintain standing water 2–5 cm during early growth",
            "Split nitrogen in 2–3 doses (basal + tillering + panicle)",
            "Weed control within first 30 days is critical",
        ],
        "tips": [
            "Prefer puddled/transplanted fields for better weed suppression",
            "Watch for leaf folder and blast in humid conditions",
            "Avoid water stress at flowering stage",
        ],
    },
    {
        "name": "Wheat",
        "season": "Rabi",
        "ph": (6.0, 7.5),
        "temp": (10, 25),
        "humidity": (40, 70),
        "rain": (20, 80),
        "essentials": [
            "Irrigate at crown-root initiation (CRI) stage (20–25 days)",
            "Balanced NPK improves grain filling and yield",
            "Ensure good drainage to avoid root diseases",
        ],
        "tips": [
            "Avoid late sowing to reduce heat stress at grain filling",
            "Monitor for rust and aphids",
            "Keep field weed-free before first irrigation",
        ],
    },
    {
        "name": "Maize",
        "season": "Kharif/Rabi",
        "ph": (5.8, 7.2),
        "temp": (18, 32),
        "humidity": (40, 75),
        "rain": (50, 150),
        "essentials": [
            "Ensure proper spacing for aeration and light",
            "Nitrogen split is important (knee-high + tasseling)",
            "Avoid waterlogging in early stage",
        ],
        "tips": [
            "Scout for fall armyworm/borer and act early",
            "Keep soil moist during tasseling/silking",
            "Use mulching in dry spells",
        ],
    },
    {
        "name": "Soybean",
        "season": "Kharif",
        "ph": (6.0, 7.5),
        "temp": (20, 35),
        "humidity": (50, 85),
        "rain": (60, 200),
        "essentials": [
            "Ensure good drainage (soybean is sensitive to waterlogging)",
            "Rhizobium inoculation improves yield",
            "Timely weeding (first 30 days) is critical",
        ],
        "tips": [
            "Scout for girdle beetle and stem fly",
            "Avoid late sowing to reduce disease pressure",
            "Maintain plant population for better canopy closure",
        ],
    },
    {
        "name": "Groundnut",
        "season": "Kharif",
        "ph": (5.5, 7.0),
        "temp": (20, 35),
        "humidity": (50, 85),
        "rain": (50, 180),
        "essentials": [
            "Calcium (gypsum) at flowering improves pod filling",
            "Avoid water stress during pegging stage",
            "Maintain loose soil for pegging",
        ],
        "tips": [
            "Monitor leaf spot and rust; apply fungicide if needed",
            "Avoid waterlogging; improves pod rot resistance",
            "Practice crop rotation to reduce pests",
        ],
    },
    {
        "name": "Cotton",
        "season": "Kharif",
        "ph": (6.0, 8.0),
        "temp": (21, 38),
        "humidity": (40, 75),
        "rain": (40, 120),
        "essentials": [
            "Avoid excess nitrogen (causes vegetative growth)",
            "Maintain timely pest scouting (bollworm/whitefly)",
            "Intercultural operations improve soil aeration",
        ],
        "tips": [
            "Use pheromone traps for bollworm monitoring",
            "Maintain field sanitation and remove infested bolls",
            "Avoid late irrigation near harvest",
        ],
    },
    {
        "name": "Mustard",
        "season": "Rabi",
        "ph": (6.0, 7.8),
        "temp": (10, 25),
        "humidity": (35, 70),
        "rain": (20, 80),
        "essentials": [
            "Sulphur improves oil content (apply if possible)",
            "Irrigate at flowering/pod formation if moisture stress",
            "Avoid late sowing for higher yield",
        ],
        "tips": [
            "Monitor for aphids; early spray if infestation high",
            "Proper spacing reduces humidity-related diseases",
            "Use clean seed to avoid Alternaria blight",
        ],
    },
    {
        "name": "Chickpea",
        "season": "Rabi",
        "ph": (6.0, 8.0),
        "temp": (15, 30),
        "humidity": (30, 65),
        "rain": (20, 80),
        "essentials": [
            "Avoid excess irrigation (wilt risk)",
            "Seed treatment reduces soil-borne diseases",
            "Provide one irrigation at flowering if dry",
        ],
        "tips": [
            "Watch for pod borer during flowering/podding",
            "Keep field clean to reduce disease carryover",
            "Use Rhizobium inoculation for better nitrogen fixation",
        ],
    },
    {
        "name": "Millet (Bajra)",
        "season": "Kharif",
        "ph": (5.5, 8.0),
        "temp": (20, 40),
        "humidity": (30, 70),
        "rain": (20, 90),
        "essentials": [
            "Drought tolerant but needs moisture at flowering",
            "Avoid heavy waterlogging soils",
            "Maintain optimal spacing for better ear development",
        ],
        "tips": [
            "Monitor downy mildew; use resistant varieties if possible",
            "One irrigation at flowering improves grain set",
            "Apply organic matter to improve soil structure",
        ],
    },
    {
        "name": "Tomato",
        "season": "All",
        "ph": (6.0, 7.0),
        "temp": (18, 30),
        "humidity": (40, 70),
        "rain": (30, 120),
        "essentials": [
            "Staking improves airflow and reduces fruit rot",
            "Balanced potassium improves fruit quality",
            "Avoid overwatering to prevent fungal diseases",
        ],
        "tips": [
            "Mulch to reduce evaporation and weeds",
            "Monitor for leaf curl/whiteflies",
            "Calcium spray helps reduce blossom end rot",
        ],
    },
    {
        "name": "Potato",
        "season": "Rabi",
        "ph": (5.0, 6.5),
        "temp": (12, 24),
        "humidity": (50, 85),
        "rain": (30, 120),
        "essentials": [
            "Earthing up improves tuber formation",
            "Avoid water stress during tuber initiation",
            "Use disease-free seed tubers",
        ],
        "tips": [
            "Monitor late blight in cool humid weather",
            "Proper spacing avoids humidity buildup",
            "Stop irrigation 10–12 days before harvest",
        ],
    },
]
